### ISSUE TITLE
Integration Test Failure

### ISSUE THREAD

**Issue by navneetlakra** [near-examples/wallet-example#41]
Integration tests (yarn jest) wallet-example fail with following error:
![image](https://user-images.githubusercontent.com/10936810/80673978-fe847100-8af3-11ea-87b9-807b5ab2e74d.png)

**Comment by chadoh** [comment]
Thanks for the report, @navneetlakra! Looks like we may have had some failures for a while even in our CI environment: https://travis-ci.com/github/near-examples/wallet-example/branches

However, it's passing there now, and it's passing for me when I run tests locally

Can you retry and let me know if you're still seeing this problem?

**Comment by navneetlakra** [comment]
Thanks for the update @chadoh. I tested it again in Gitpod. yarn jest works fine now. 

However, the yarn asp fails with following. I am not sure if this is a Gitpod specific problem.

```
gitpod /workspace/wallet-example $ yarn asp
yarn run v1.22.0
warning package.json: No license field
$ asp --verbose
       ___   _____                       __    
      /   | / ___/      ____  ___  _____/ /_   
     / /| | \__ \______/ __ \/ _ \/ ___/ __/   
    / ___ |___/ /_____/ /_/ /  __/ /__/ /_     
   /_/  |_/____/     / .___/\___/\___/\__/     
                    /_/                        

⚡AS-pect⚡ Test suite runner [3.1.4]

[Log] Loading asc compiler
[Log] Compiler loaded in 653.725ms.
[Log] Using configuration /workspace/wallet-example/as-pect.config.js
Error: unrecognized flag --experimental-wasm-bigint
Try --help for options
[Log] Using VerboseReporter
[Log] Including files: assembly/__tests__/**/*.spec.ts
[Log] Running tests that match: (:?)
[Log] Running groups that match: (:?)
[Log] Effective command line args:
  [TestFile.ts] node_modules/@as-pect/assembly/assembly/index.ts node_modules/near-sdk-as/assembly/vm/vm.include.ts --validate --debug --binaryFile output.wasm --runtime stub --baseDir /workspace/wallet-example --runPasses inlining,dce --transform /workspace/wallet-example/node_modules/near-sdk-as/bindgen,/workspace/wallet-example/node_modules/@as-pect/core/lib/transform/index.js --explicitStart --use ASC_RTRACE=1 --exportTable --importMemory

/workspace/wallet-example/node_modules/@as-pect/core/lib/util/wasmTools.js:58
        var mod = new WebAssembly.Module(contents);
                  ^

CompileError: WebAssembly.Module(): Wasm decoding failed: mutable globals cannot be exported @+1718
    at new NameSection (/workspace/wallet-example/node_modules/@as-pect/core/lib/util/wasmTools.js:58:19)
    at new TestContext (/workspace/wallet-example/node_modules/@as-pect/core/lib/test/TestContext.js:166:32)
    at runBinary (/workspace/wallet-example/node_modules/@as-pect/cli/lib/run.js:386:26)
    at /workspace/wallet-example/node_modules/@as-pect/cli/lib/run.js:626:42
    at Object.main (/workspace/wallet-example/node_modules/assemblyscript/cli/asc.js:998:10)
    at /workspace/wallet-example/node_modules/@as-pect/cli/lib/run.js:577:17
    at Array.forEach (<anonymous>)
    at run (/workspace/wallet-example/node_modules/@as-pect/cli/lib/run.js:575:36)
    at Object.asp (/workspace/wallet-example/node_modules/@as-pect/cli/lib/index.js:63:9)
    at Object.<anonymous> (/workspace/wallet-example/node_modules/@as-pect/cli/bin/asp:2:28)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
